import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E4-HMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/purple-house.svg" type="image/svg+xml" />
        <meta name="theme-color" content="#f5e6fa" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
